### PR TITLE
Put build-time settings in separate include

### PR DESCRIPTION
**Pull request by rbergen**
This puts the build-time configuration options in a separate include file. This makes them easier to identify and change.

### CODE REVIEW

**Review by davepl — DISMISSED** [review]
Can you detab?  We should be on tabs == 8 with an indent of 4, but no actual tab chars in the file if possible.  The spacing is all whacky on my machine where tabs are 8, as God intended them to be.

**Comment by rbergen** [comment]
I sure can. For the record: as far as I'm aware, the only tab chars that are in petclock.asm are the ones that were already in there when I started working on it (as in, when I made my first edits to your original). The reason I maintained them is to prevent PRs with mountains of whitespace-only changes. Which is what this PR will turn into now that I'll deliberately convert tabs into spaces.

**Comment by davepl** [comment]
I guess they came from me, which is weird because I don’t use tabs!  You could separate the detab into a different delta, but I doubt it matters.  Strip out the tabs, I say!

- Dave

**Comment by rbergen** [comment]
Done and dusted. In the files I changed, there should be no tab characters left.
Concerning the source of the tabs, it could be rooted in a copy & paste of the basis for the petSD+ writing and reading routines. It looks like those routines are where the majority of the tab characters remained after the edits I already made.

**Comment by rbergen** [comment]
Hang on... VS Code only replaced leading (indentation) tabs. It looks like it doesn't actually have a feature to replace all embedded tabs in all lines, while preserving the correct spacing. I'm going to come back to this once I've found a way to sort this without going bonkers.

**Comment by rbergen** [comment]
Notepad++ to the rescue. I think this time we _are_ done.

(The reason I didn't see things were still out of whack is that I had installed a browser plugin that replaces tabs with 4 spaces instead of 8, when viewing files on GitHub. Sometimes I'm too clever for my own good...)

**Review by davepl — APPROVED** [review]
To the extent one can review empty whitespace, it 'looks' good to me!

**Pull request merged**
