### PR TITLE
Add C64 support

### PR DESCRIPTION
**Pull request by rbergen**
This adds support for the Commodore 64, as verified on the VICE C64 emulator. Although it is possible to use the petSD+ on the Commodore 64, this version of the PET Clock does not include support for it. The reason is that me not having a Commodore 64 or a petSD+, there is no way for me to test any attempt at making it work.

I've made the text color on the C64 configurable in settings.inc, and it can be changed while the clock is running.

### CODE REVIEW

**Review by davepl — COMMENTED** [review]
MINUTE_JIFFIES = SECOND_JIFFIES * 60 is another option :-)

**Comment by rbergen** [comment]
> MINUTE_JIFFIES = SECOND_JIFFIES * 60 is another option :-)

You're absolutely right. If I remember this comment when I make my next change to the clock, I might even implement it like that. :)

**Comment by davepl** [comment]
Mostly just showing I’m paying attention :-)

**Review by davepl — COMMENTED** [review]
Looks good!

**Pull request merged**
